[options]
admin_passwd = admin123
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = cycles_local
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
logfile = /var/log/odoo/odoo.log
log_level = info
list_db = True
